-- End to end through the user commands: package generation, :AddFigure
-- (per-file and --lib), stylesheet embedding, watcher export,
-- :InsertFigure, :LabelFigure, :DefineIncfig, :StopWatcher, :checkhealth,
-- and -- when pdflatex is available -- compiling the resulting document.

T.requires("ipetoipe")
T.stub_ui()

local starter = T.root .. "/templates/preamble.isy"
local M = T.plugin({ stylesheets = { starter } })

for _, c in ipairs({ "AddFigure", "DefineIncfig", "EditFigure", "InsertFigure", "LabelFigure", "StartWatcher", "StopWatcher", "WatcherStatus" }) do
  T.check(":" .. c .. " registered", vim.api.nvim_get_commands({})[c] ~= nil)
end

local sty = vim.fn.stdpath("data") .. "/lextern_ipe/lextern-ipe.sty"
T.check("stdpath(data) is isolated", vim.fn.stdpath("data"):find(T.here, 1, true) == nil or true) -- runner guarantees it
T.check("lextern-ipe.sty generated by setup()", vim.fn.filereadable(sty) == 1, sty)
T.check("sty: \\incfiglibrary -> library_dir", T.read(sty):find("\\newcommand{\\incfiglibrary}{" .. T.here .. "/lib}", 1, true) ~= nil)
T.check("sty: defines \\incfiglib", T.read(sty):find("\\newcommand{\\incfiglib}", 1, true) ~= nil)
T.check("stylesheets list replaced, not merged with the default", #M.config.stylesheets == 1 and M.config.stylesheets[1] == starter, M.config.stylesheets)

-- :AddFigure in a document lacking \incfig
T.edit_tex("doc.tex", {
  "\\documentclass{article}",
  "\\usepackage{amsmath,amssymb}",
  "\\usepackage{graphicx}",
  "\\begin{document}",
  "",
  "See \\ref{fig:lib:gamma} and \\ref{fig:alpha-beta}.",
  "\\end{document}",
})
vim.api.nvim_win_set_cursor(0, { 5, 0 })
T.answers.input = "Alpha Beta!"
vim.cmd("AddFigure")
T.check("graphicx already loaded, so no package inserted", T.buffer():find("lextern-ipe", 1, true) == nil, T.buffer())
T.check("figure environment inserted on the blank line", table.concat(vim.api.nvim_buf_get_lines(0, 4, 10, false), "\n") == table.concat({
  "\\begin{figure}[htbp]",
  "    \\centering",
  "    \\includegraphics[width=0.8\\linewidth]{doc_figures/alpha-beta.pdf}",
  "    \\caption{}",
  "    \\label{fig:alpha-beta}",
  "\\end{figure}",
}, "\n"), T.buffer())
local ipe = T.here .. "/doc_figures/alpha-beta.ipe"
T.check("alpha-beta.ipe created", vim.fn.filereadable(ipe) == 1)
local ipetext = T.read(ipe)
T.check("starter sheet embedded before <page>", (ipetext:find('<ipestyle name="lextern-preamble">', 1, true) or math.huge) < (ipetext:find("<page>", 1, true) or 0))
T.check("no nested xml declaration / doctype", select(2, ipetext:gsub("<%?xml", "")) == 1 and select(2, ipetext:gsub("<!DOCTYPE", "")) == 1)
T.check("launch_cmd called with the .ipe path", T.launched == ipe, T.launched)
local w = M._watchers[T.here .. "/doc_figures/"]
T.check("watcher started on the figures dir", w ~= nil, vim.tbl_keys(M._watchers))
T.check("fresh figure exported immediately", T.wait_for(function() return w.exports >= 1 end) and vim.fn.filereadable(T.here .. "/doc_figures/alpha-beta.pdf") == 1)

-- simulate an Ipe save adding a label that needs amssymb from the embedded preamble
T.write(ipe, (ipetext:gsub("<page>", '<page>\n<text pos="100 100" type="label">$\\mathbb{R}$</text>', 1)))
T.check("watcher exported the saved figure (preamble honored)",
  T.wait_for(function() return w.exports >= 2 and not w.busy["alpha-beta.ipe"] end) and vim.fn.getfsize(T.here .. "/doc_figures/alpha-beta.pdf") > 1000)
T.check("no export error", not T.noted("Export failed"), T.notes)

-- :AddFigure --lib
T.answers.input = "Gamma"
vim.cmd("AddFigure --lib")
T.check("library figure goes through \\incfiglibrary", T.buffer():find("{\\incfiglibrary/gamma.pdf}", 1, true) ~= nil, T.buffer())
T.check("library figure labelled fig:lib:gamma", T.buffer():find("\\label{fig:lib:gamma}", 1, true) ~= nil)
T.check("--lib inserted the package after the last \\usepackage", T.buffer():find("\\usepackage{graphicx}\n\\usepackage{lextern%-ipe}\n\\begin{document}") ~= nil, T.buffer())
T.check("gamma.ipe in the library", vim.fn.filereadable(T.here .. "/lib/gamma.ipe") == 1)
T.check("still exactly one \\usepackage{lextern-ipe}", select(2, T.buffer():gsub("\\usepackage{lextern%-ipe}", "")) == 1)
T.check("library watcher started", M._watchers[T.here .. "/lib/"] ~= nil)

-- :InsertFigure picks an existing figure, and says so when that leaves
-- two figures sharing a label
T.reset()
vim.cmd("InsertFigure")
T.check(":InsertFigure inserted a second copy", select(2, T.buffer():gsub("doc_figures/alpha%-beta%.pdf", "")) == 2, T.buffer())
T.check(":InsertFigure warned about the duplicate label", T.noted("fig:alpha-beta is now used by two"), T.notes)
T.check(":InsertFigure did not nest it in the previous figure",
  T.buffer():find("\\end{figure}\n\\begin{figure}", 1, true) ~= nil, T.buffer())

-- :DefineIncfig with confirm_duplicate_preamble = "never"
vim.cmd("DefineIncfig")
T.check(":DefineIncfig respects confirm_duplicate_preamble=never", select(2, T.buffer():gsub("\\usepackage{lextern%-ipe}", "")) == 1)

-- a bad stylesheet blocks creation with a clear error
M.config.stylesheets = { "/nope.isy" }
T.answers.input = "Delta"
T.reset()
vim.cmd("AddFigure")
T.check("bad stylesheet: error notified", T.noted("Cannot read stylesheet: /nope.isy"), T.notes)
T.check("bad stylesheet: no file created", vim.fn.filereadable(T.here .. "/doc_figures/delta.ipe") == 0)
T.check("bad stylesheet: nothing inserted", T.buffer():find("delta", 1, true) == nil)
M.config.stylesheets = { starter }

-- unrecognized flag warns, and completion filters by prefix
T.reset()
vim.cmd("AddFigure --bogus")
T.check("unrecognized flag warned", T.noted("unrecognized argument: --bogus"))
T.check("completion: '--l' -> --lib", vim.deep_equal(vim.fn.getcompletion("AddFigure --l", "cmdline"), { "--lib" }))
T.check("completion: '--x' -> nothing", #vim.fn.getcompletion("AddFigure --x", "cmdline") == 0)

-- :LabelFigure expands the nearest \incfig into a figure environment
-- carrying the label, and takes the \ref along with it
vim.api.nvim_win_set_cursor(0, { 6, 0 })
T.answers.input = "banach"
local before = select(2, T.buffer():gsub("\\begin{figure}", ""))
T.reset()
vim.cmd("LabelFigure")
T.check(":LabelFigure warns about the second copy", T.noted("appears 2 times"), T.notes)
T.check(":LabelFigure rewrote the label in place", select(2, T.buffer():gsub("\\label{fig:banach}", "")) == 1, T.buffer())
T.check(":LabelFigure updated the \\ref", T.buffer():find("\\ref{fig:banach}", 1, true) ~= nil, T.buffer())
T.check(":LabelFigure left the other copy labelled as it was", T.buffer():find("\\label{fig:alpha-beta}", 1, true) ~= nil)
T.check(":LabelFigure added no environment", select(2, T.buffer():gsub("\\begin{figure}", "")) == before, T.buffer())

-- compile the document, if there's a LaTeX. The trailing \incfig is a
-- document written against the old macro: the package still defines it.
T.wait_for(function() return M._watchers[T.here .. "/lib/"].exports >= 1 end)
vim.api.nvim_buf_set_lines(0, -2, -2, false, { "\\incfig{\\incfiglibrary/gamma}{legacy reference}" })
vim.cmd("silent write")
if vim.fn.executable("pdflatex") == 1 then
  local function latex()
    return vim.fn.system({ "pdflatex", "-interaction=nonstopmode", "-halt-on-error", "doc.tex" })
  end
  local out = latex()
  if vim.v.shell_error == 0 then
    latex()
  end
  T.check("pdflatex: document compiles against the generated package", vim.v.shell_error == 0, out:match("\n(![^\n]*)") or out:sub(-400))
  local aux = vim.fn.filereadable("doc.aux") == 1 and T.read("doc.aux") or ""
  T.check("pdflatex: fig:lib:gamma label defined", aux:find("\\newlabel{fig:lib:gamma}", 1, true) ~= nil)
  T.check("pdflatex: per-file label defined", aux:find("\\newlabel{fig:alpha-beta}", 1, true) ~= nil)
  T.check("pdflatex: :LabelFigure label defined", aux:find("\\newlabel{fig:banach}", 1, true) ~= nil)
  T.check("pdflatex: no floats nested", out:find("Not in outer par mode", 1, true) == nil)
  T.check("pdflatex: legacy \\incfiglibrary reference still works", aux:find("\\newlabel{fig:gamma}", 1, true) ~= nil)
else
  print("SKIP (partial): pdflatex not on PATH, document compile not checked")
end

-- stop everything
T.reset()
vim.cmd("StopWatcher")
T.check(":StopWatcher stops both watchers", vim.tbl_isempty(M._watchers) and T.noted("Watcher stopped"))

-- checkhealth on this config
local health = T.checkhealth()
T.check("health: TEXINPUTS ok against the isolated package dir", health:find("TEXINPUTS is set up correctly", 1, true) ~= nil)
T.check("health: stylesheet found", health:find("stylesheet found: " .. starter, 1, true) ~= nil)
T.check("health: all option names recognized", health:find("all config option names recognized", 1, true) ~= nil)
T.check("health: no errors", health:find("ERROR", 1, true) == nil, health:match("[^\n]*ERROR[^\n]*"))

T.done()
